trigger:
- main  # Runs the pipeline when the main branch is updated

pool:
  vmImage: 'ubuntu-latest'  # Use Microsoft-hosted agent

variables:
  resourceGroupName: 'amir'
  dataFactoryName: 'secondadff'
  location: 'Canada Central'  # Change based on your region
  templateFile: 'ARMTemplateForFactory.json'
  parametersFile: 'ARMTemplateParametersForFactory.json'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy ARM Template to ADF'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'connectionboi'  # Create this in DevOps
    subscriptionId: '1cf1a497-23f9-40eb-8a05-e23b72149b49'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(templateFile)'
    csmParametersFile: '$(parametersFile)'
    deploymentMode: 'Incremental'  # Ensures only changes are deployed